netlify/netlify-plugin-gatsby

src/helpers/config.js
src/index.js
test/fixtures/functions-without-gatsby-plugin/.gitignore
test/fixtures/functions-without-gatsby-plugin/_redirects

Git normalizes line endings when checking files in and out. The current implementation generates a gitignore with CRLF. This is converted to LF when checked-in, which means that when we check on the next build it doesn't recognise that it has already been added, so generates a duplicate. This PR switches to a more robust system that uses a start and end marker and can handle different sorts of line ending

fix: handle gitignore line endings

---

README.md

This docs PR adds a note to help users who may want to install this plugin manually but already have Gatsby Cache build plugin installed on their site.
For newly linked sites, this plugin would get installed first, so it's not really a concern.

docs: adds Gatsby Cache note to readme

---

plugin/package.json

This PR adds a `bugs` URL to the plugin's package.json
**Checklist**
seen below.

fix(plugin-package-json): add bugs url

---

package-lock.json
plugin/package-lock.json

With our recent fork of `netlify/esbuild`, the version `0.13.5` has some problems and fails to install locally.
This PR fixes this by updating `package-lock.json`.

chore: fix `package-lock.json`

---

demo/package.json
plugin/test/fixtures/custom-functions-directory/.gitignore
plugin/test/fixtures/custom-functions-directory/.netlify/state.json
plugin/test/fixtures/custom-functions-directory/package.json
plugin/test/fixtures/functions-without-gatsby-plugin/.gitignore
plugin/test/fixtures/functions-without-gatsby-plugin/.netlify/state.json
plugin/test/fixtures/functions-without-gatsby-plugin/package.json
plugin/test/fixtures/no-functions/.netlify/state.json
plugin/test/fixtures/with-no-gatsby-config/.netlify/state.json
plugin/test/fixtures/with-no-plugins/.gitignore
plugin/test/fixtures/with-no-plugins/.netlify/state.json
plugin/test/fixtures/with-old-gatsby-plugin/.gitignore
plugin/test/fixtures/with-old-gatsby-plugin/.netlify/state.json
plugin/test/fixtures/with-old-netlify-plugin/.gitignore
plugin/test/fixtures/with-old-netlify-plugin/.netlify/state.json

Use the new `--offline` flag for builds rather than passing a fake token, which seems to be breaking tests

fix: use offline build instead of fake token

---

plugin/src/index.js

Fix a bug seen a few times in Bugsnag where the user's Gatsby config includes null entries in the plugins array

fix: handle null plugin entries

---

.gitignore
demo/.env.development
demo/package.json
plugin/src/index.js
plugin/src/templates/__gatsby-functions.ts
plugin/src/templates/createResponseObject.js
plugin/src/templates/functions.js
plugin/src/templates/gatsbyFunction.js
plugin/test/fixtures/custom-functions-directory/e2e-tests/__snapshots__/functions.test.js.snap
plugin/test/fixtures/custom-functions-directory/e2e-tests/test-helpers.js
plugin/test/fixtures/custom-functions-directory/src/api/i-am-text.js
plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/__snapshots__/functions.test.js.snap
plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/functions.test.js
plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/test-helpers.js
plugin/test/fixtures/functions-without-gatsby-plugin/src/api/i-am-text.js

In `dev`, only proxy the fucntion to gatsby develop if the compiled file doesn't exist, otherwise serve it directly like in prod.

fix: conditionally proxy dev functions

---

.github/workflows/test.yml
.gitignore
demo/package.json
plugin/.gitignore
plugin/package-lock.json
plugin/package.json
plugin/src/index.js

This PR adds a build step using Parcel 2 to enable us to use ESM and TS. This will eventually be supported natively in plugins, but until then we will build to CJS

chore: add build step to support ts and esm

---

README.md

AWS_LAMBDA_JS_RUNTIME defaults to 14 now so we can remove this note from the docs

Remove docs on setting AWS_LAMBDA_JS_RUNTIME

---

demo/netlify.toml

The build needs to run without `ignore` set at least once, otherwise it will keep skipping builds.

chore: temporarily disable `build.ignore`

---

demo/src/pages/500.js
demo/src/pages/bad-dog.js
demo/src/pages/index.js
plugin/src/helpers/config.ts
plugin/src/templates/handlers.ts
plugin/src/templates/utils.ts
plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/test-helpers.js

Adds better error handling, including support for [custom 500 error pages](https://www.gatsbyjs.com/docs/how-to/adding-common-features/add-500-page/)
1. Visit deploy preview
2. Click on "Error Page"
3. Observe a custom error page

feat: add support for custom error pages

---

plugin/package-lock.json
plugin/package.json
plugin/src/helpers/config.ts
plugin/src/helpers/verification.ts
plugin/src/index.ts

Adds logging of largest files if the function zips are larger than 50MB. Also excludes all `*js.map` files by default.
Fixes #167

feat: handle large zipfiles

---

.prettierignore
README.md
demo/netlify.toml
demo/package.json
plugin/package-lock.json
plugin/package.json
plugin/src/helpers/functions.ts
plugin/src/index.ts
plugin/src/templates/ipx.ts
plugin/test/fixtures/functions-without-gatsby-plugin/package.json
plugin/test/fixtures/no-functions/package.json
plugin/test/fixtures/with-no-gatsby-config/package.json
plugin/test/fixtures/with-no-plugins/package.json
plugin/test/fixtures/with-old-gatsby-plugin/package.json
plugin/test/fixtures/with-old-netlify-plugin/package.json

Adds support for Gatsby [Image CDN](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-utils#add-imagecdn-support). We do this using [@netlify/ipx](https://github.com/netlify/netlify-ipx), which now has support for Gatsby's base64-encoded params.
This PR adds an ODB with `@netlify/ipx`, and a rewrite from `/_gatsby/image/*` to that builder. It also sets the env var `GATSBY_CLOUD_IMAGE_CDN`, which enables this feature. 
The version in this PR can be installed as `@netlify/plugin-gatsby@images`. For a live example using that release see: https://gatsby-image-cdn-demo.netlify.app/
[Example image](https://deploy-preview-303--netlify-plugin-gatsby-demo.netlify.app/_gatsby/image/aHR0cHM6Ly9pbWFnZXMudW5zcGxhc2guY29tL3Bob3RvLTE1MTc4NDk4NDU1MzctNGQyNTc5MDI0NTRhP2l4bGliPXJiLTEuMi4 …

feat: image cdn support

---

plugin/src/helpers/functions.ts
plugin/src/templates/ipx.ts

The Gatsby image CDN feature also supports proxying files via `/_gatsby/file/...`. Rather than proxying them, this PR implements them as a redirect for simplicity and performance.
To test, click [this link](https://deploy-preview-305--netlify-plugin-gatsby-demo.netlify.app/_gatsby/file/aHR0cHM6Ly9pbWFnZXMudW5zcGxhc2guY29tL3Bob3RvLTE1MTc4NDk4NDU1MzctNGQyNTc5MDI0NTRhP2l4bGliPXJiLTEuMi4xJml4aWQ9TW53eE1qQTNmREI4TUh4d2FHOTBieTF3WVdkbGZIeDhmR1Z1ZkRCOGZIeDgmYXV0bz1mb3JtYXQmZml0PWNyb3Amdz0yMDAwJnE9ODA=/photo-1517849845537.jpg) and check that it redirects to Unsplash:

feat: add support for `/_gatsby/file/*` redirects

---

README.md
docs/image-cdn.md
plugin/src/helpers/functions.ts
plugin/src/index.ts

Now that the image CDN is live we need to make a few changes. First, because it turns out that support is still only in the prerelease version, we will no longer enable it by default. We also have more details on usage, so I have expanded the docs.

fix: update image CDN docs and defaults

---

plugin/src/helpers/files.ts

The fix for #294 did not cover all cases. Specifically, the `lmdb` module was resolving the incorrect path, so when using a version of Gatsby that uses it, we were trying to look in the wrong place for the binaries. We need to know their location because we copy them into the function bundle. This fix handles the case where `lmdb` resolves its root to the subdirectory, by looking a level up.

fix: resolve lmdb binaries correctly

---

README.md
plugin/package-lock.json
plugin/package.json
plugin/src/helpers/config.ts
plugin/src/helpers/files.ts
plugin/src/index.ts

BREAKING CHANGE: DSG pages are now discretely redirected to the handler function, rather than via a catch-all redirect. This PR removes the catch-all redirect and moves DSG handling to [netlify/gatsby-plugin-netlify](https://github.com/netlify/gatsby-plugin-netlify), making that plugin a requirement for DSG pages.
This change ensures that 404 pages aren't unnecessarily handled via SSR and ensures they work when a site has functions but no SSR/DSG bundle.
1. The demo in the repo isn't able to provide a case for 'Functions but no SSR/DSG', so a new Gatsby test site is needed with that configuration.
2. 404 page should render successfully without being redirected to the handler function.
Fixes #330 
---
🧪 Once merged, make sure to update the version if needed and that it was published …

fix!: remove catch-all DSG redirect and handle discretely

---

plugin/src/helpers/config.ts
plugin/src/helpers/files.ts
plugin/src/helpers/functions.ts
plugin/src/index.ts

This PR switches `shouldSkipFunctions()` for `getNeededFunctions()` which checks the skip file generated by gatsby-plugin-netlify and returns an array of the required functions, rather than a boolean.
This array is then used throughout the remaining function setup code to enable each function individually.
Backward compatibility is maintained by disabling all functions if an empty skip file is provided and enabling all functions if no skip file exists.
The current env var `NETLIFY_SKIP_GATSBY_FUNCTIONS` still disables all functions as before, but 3 additional env vars have been added to control each function individually:
`NETLIFY_SKIP_API_FUNCTION`
`NETLIFY_SKIP_SSR_FUNCTION`
`NETLIFY_SKIP_DSG_FUNCTION`
* A site with no functions requirements should not generate any functions
* A site …

feat: enable API, SSR and DSG functions individually as required

---

plugin/src/helpers/files.ts

In v2.4.0 of `lmdb`, the platform binary package names transition over to scoped names ([release notes here](https://github.com/kriszyp/lmdb-js/releases/tag/v2.4.0)).
This change supports the transition to those scoped names for newer versions of Gatsby.
**Note:** This depends on https://github.com/gatsbyjs/gatsby/pull/36087 being merged. The current version of `lmdb` pinned in Gatsby is missing the GLIBC binaries for Node 14 and 16 and needs to upgraded in order for this change to address issues reported by users about encountering GLIBC errors on DSG/SSR pages on their Gatsby sites.
Using a website provided by a customer, this was tested by:
* Installing `lmdb@2.5.3` as a top level dependency on the customer's website
* Publishing a version of the plugin containing these changes but …

fix: support scoped names for platform binary packages in lmdb

---

demo/package-lock.json
plugin/test/unit/helpers/config.spec.ts
plugin/test/unit/templates/utils.spec.ts

The unit tests for this plugin have been failing for a while. With digging, it appears that the cleanup process of deleting the temporary directory takes more than 5 seconds which causes a timeout in the `afterEach` hook. In profiling the cleanup function, it appears to take ~5500 ms.
This PR increases adds an increased test timeout of 6 seconds to the `afterEach` function to ensure cleanup completes.
Ensure that the unit tests execute without timeout errors.

test: fix unit tests

---

plugin/src/helpers/config.ts
plugin/src/index.ts
plugin/test/helpers.js
plugin/test/unit/helpers/config.spec.ts
plugin/test/unit/index.spec.ts
plugin/test/unit/templates/utils.spec.ts

Doesn't attempt a lambda pre-warm request if the `DEPLOY_PRIME_URL` is not set. This will address issues in our CI environment where we're attempting to make these requests for a non-existent site
Should see no pre-warm requests be attempted within our CI test suite, but still see them made when the `GATSBY_EXCLUDE_DATASTORE_FROM_BUNDLE` variable is set and a deploy is being made for a netlify site.
Fixes [this issue](https://github.com/netlify/pod-ecosystem-frameworks/issues/138)
---

feat: do not pre-warm lambdas if DEPLOY_PRIME_URL is not set

---

plugin/src/templates/utils.ts
plugin/test/unit/templates/utils.spec.ts

When redirecting filesystem paths using the `linkfs` package, `fs.promises` is not included in the [redirected or proxied paths](https://github.com/streamich/linkfs/blob/50f95d1d125cede14e684457466e23434a73a0e0/src/index.ts), resulting in a "Cannot destructure property 'readFile' of 'fs_1.promises' " error on SSR pages.
This change makes `promises` is available on the global `_fsWrapper` property that is used by Gatsby. This ensures that underlying Gatsby dependencies (specifically [`graphql-tools`](https://github.com/ardatan/graphql-tools/blob/5931dc7d103ecfe16e479d652c43f0e69270d169/packages/loaders/code-file/src/index.ts#L27) in this case) have this available.
[Deploy preview](https://ep-gatsby-read-file-issue.netlify.app/using-ssr/) - this page should render successfully
Fixes …

fix: add fs.promises to linked filesystem

---

README.md

Clarify that the background and scheduled functions are netlify functions, not gatsby ones.

docs: clarify type of function in README

---

plugin/src/helpers/functions.ts
plugin/test/unit/helpers/functions.spec.ts

If the functions-internal directory doesn't exist before trying to copy in the ipx.ts file, the build fails. This checks for and adds that directory if needed before copying files.
1. Set build script to `GATSBY_CLOUD_IMAGE_CDN=1 gatsby build`
2. Run `netlify deploy --build` and it should not fail.
Closes https://github.com/netlify/netlify-plugin-gatsby/issues/546
Related: https://github.com/netlify/pod-ecosystem-frameworks/issues/307

fix: add functions-internal directory if missing

---

.github/workflows/pre-release.yml

GitHub is [deprecating the `set-output` workflow command](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) in actions after 31st May 2023.
This PR changes the GitHub workflow to use the new format. 
1. Check that the PR actions work as expected with a pre-release
---

chore: fix deprecated set-output github workflow command

---

plugin/src/index.ts
plugin/src/templates/handlers.ts

When using the current plugin version with Gatsby V2, users were running into this error:
With the previous Dynamic import update, there were issues that could have emerged when placing the `deleteFunctions` within the conditional. This new change converts the `getApiHandler` function (where reach-router is being called) into a string and prevents reach-router from being required as a dependency for v2 sites. 
`makeApiHandler` contains `getApiHandler` and is only called when creating a function. 
1. Can test it with a V2 site and make sure the above error doesn't appear 
- Example site: https://github.com/taty2010/gatsby-v2-test (will need to uninstall @gatsbyjs/reach-router)
Ref: https://github.com/netlify/netlify-plugin-gatsby/issues/556
---
🧪 Once merged, make sure to update the …

fix: prevent reach-router dep requirement for v2

---

demo-v5/package-lock.json
demo/package-lock.json
plugin/package-lock.json
plugin/package.json

Just making sure we use latest `@netlify/ipx` (with https://github.com/netlify/netlify-ipx/pull/136 ). Current version range accept it, but package manager might still use older version if there is cached `node_modules` (or similar)
1. Visit the Deploy Preview ([insert link to specific page]()) ...
---

chore(deps): update @netlify/ipx to ^1.4.0

---

plugin/src/helpers/verification.ts

1. Visit the Deploy Preview ([insert link to specific page]()) ...
---

fix: make large lambda warning message more informative

---

.github/workflows/test.yml

There is some problem with latest CLI and our tests. Not clear yet where the problem actually is, but for now to unblock unrelated work let's pin (hopefully temporarily) CLI version we are using in tests, until we fix either the CLI or the tests
https://github.com/netlify/cli/pull/6180#issuecomment-1825919680 has a bit more information about the problem
1. Visit the Deploy Preview ([insert link to specific page]()) ...
---

test: pin netlify-cli to 17.6.0

---

docs/image-cdn.md

Update examples to reflect https://docs.netlify.com/image-cdn/overview/#remote-path
1. Visit the Deploy Preview ([insert link to specific page]()) ...
---

fix: update domain url docs

---

.github/workflows/test.yml
plugin/src/helpers/config.ts
plugin/src/index.ts
plugin/test/fixtures/v5/with-adapters/e2e-tests/test-helpers.js

Reverts https://github.com/netlify/netlify-plugin-gatsby/pull/724 + adds fixes needed:
`ntl dev` clears `.netlify/functions-internal` so we have to (re)generate them. Alternatively we could skip that and rely on gatsby dev server handling functions however this moves `ntl dev` further away from builds (+ there is some quirk with with CLI where `*/x-www-form-urlencoded` and `multipart/form-data` requests are not proxied to dev server at least currently).
This also clears out redirects produced by `gatsby-plugin-netlify` AND `gatsby-adapter-netlify` if builld happened before - those redirects would be for DSG/SSR functions that can't work in dev, because gatsby doesn't even produce engines in dev and DSG/SSR pages are handled just the same as SSG pages in dev
1. Visit the Deploy Preview …

fix: clear redirects/rewrites produced by previous builds and generate functions in ntl dev

---

.github/workflows/test.yml
demo-v5/package.json
demo-v5/src/pages/index.js
package-lock.json
package.json
plugin/package-lock.json
plugin/package.json
plugin/src/helpers/cache.ts
plugin/src/index.ts
plugin/test/fixtures/v4/functions-without-gatsby-plugin/e2e-tests/test-helpers.js
plugin/test/fixtures/v5/functions-without-gatsby-plugin/e2e-tests/test-helpers.js
plugin/test/fixtures/v5/with-adapters/e2e-tests/build.test.js
plugin/test/fixtures/v5/with-adapters/e2e-tests/test-helpers.js
plugin/test/fixtures/v5/with-adapters/package.json

We are currently copying `.cache` (gatsby cache dir) and `public` (gatsby publish dir) to cache directory. This results in almost doubling disk space usage for sites that produce a lot and/or heavy static assets and seems unnecessary - this change should result in lowering disk usage, but also should speed up handling of caching due to moving files and not copying them
Fixes https://linear.app/netlify/issue/FRB-1576/research-changing-netlify-plugin-gatsby-behavior-to-move-files-to
---

fix: move files to build cache after files are uploaded instead of copying them before uploads

---

demo-v5/package-lock.json
demo-v5/package.json
demo/package-lock.json
plugin/package-lock.json
plugin/src/helpers/cache.ts
plugin/src/helpers/config.ts
plugin/src/helpers/functions.ts
plugin/src/helpers/image_cdn.ts
plugin/src/index.ts
plugin/src/templates/ipx.ts
plugin/test/unit/helpers/functions.spec.ts

If image cdn is enabled:
1. If IPX is used: encrypt remote urls if used gatsby packages version support it
2. If Netlify Image CDN is used: apply allowed remote url patterns for file CDN
Additionally only setup required url patterns by used gatsby packages versions

fix: use encrypted image cdn if possible for ipx and/or use allowed remote url list

---

.github/workflows/test.yml

Leverage the latest cli in the test workflow
---

ci: unpin cli version in tests
