- .gitignore
- src/index.js
- src/templates/createRequestObject.js
- src/templates/createResponseObject.js
- src/templates/gatsby.js
- src/templates/gatsbyFunction.js
Run prettier and eslint over the codebase
> chore: format

- src/index.js
We should allow our auto-generated funcitons to overwrite themselves
> fix: allow functions to overwrite

- src/helpers/config.js
> fix: remove logs in spliceconfig

- .github/ISSUE_TEMPLATE/bug_report.md
- package-lock.json
- package.json
- src/index.js
- test/fixtures/functions-without-gatsby-plugin/.gitignore
🎉 Thanks for sending this pull request! 🎉
Please make sure the title is clear and descriptive.
If you are fixing a typo or documentation, please skip these instructions.
Otherwise please fill in the sections below.
**Which problem is this pull request solving?**
Example: I'm always frustrated when [...]
**List other issues or pull requests related to this problem**
Example: This fixes #5012
**Describe the solution you've chosen**
Example: I've fixed this by [...]
**Describe alternatives you've considered**
Example: Another solution would be [...]
**Checklist**
seen below.
> chore: renaming stuff before publish

- test/fixtures/functions-without-gatsby-plugin/package.json
🎉 Thanks for sending this pull request! 🎉
Please make sure the title is clear and descriptive.
If you are fixing a typo or documentation, please skip these instructions.
Otherwise please fill in the sections below.
**Which problem is this pull request solving?**
Example: I'm always frustrated when [...]
**List other issues or pull requests related to this problem**
Example: This fixes #5012
**Describe the solution you've chosen**
Example: I've fixed this by [...]
**Describe alternatives you've considered**
Example: Another solution would be [...]
**Checklist**
seen below.
> fix: try reordering the install script

- .github/workflows/labeler.yml
> chore: add labeler action

- README.md
Adds some info on developing with Gatsby Functions
> docs: add info on Gatsby Functions

- src/index.js
Checks for existence of compiled functions dir before trying to copy them
> fix: don't break for sites without functions enabled

- plugin/src/index.js
> feat: show build status summary

- plugin/src/index.js
Fixes #68.
This PR improves error handling as described in #68.
I did not apply Prettier+ESLint yet to make the diff easier to read for the reviewer (since it would otherwise change the indentation on many lines).
> chore: improve error handling

- README.md
- plugin/src/index.js
This runs ESLint and Prettier as mentioned in https://github.com/netlify/netlify-plugin-gatsby/pull/72
This only changes whitespaces.
> chore: run ESLint/Prettier

- commitlint.config.js
This fixes the `pre-commit` Git hook, using the same `commitlint.config.js` as our other repositories like `netlify-plugin-nextjs`.
**Checklist**
seen below.
> chore: fix commitlint

- plugin/package.json
> fix: correct publish file

- .github/workflows/release-please.yml
Fix the path for release-please
> chore: release plugin path

- plugin/package-lock.json
- plugin/package.json
release-please didn't work, so I had to do the release locally. This is the PR with the update. It doesn;t do anything, but needs merging before our next release
> chore: v2.0.1

- .github/workflows/release-please.yml
- .release-please-manifest.json
- release-please-config.json
See https://github.com/netlify/netlify-plugin-gatsby/pull/255
> ci(release-please): switch to manifest release

- package-lock.json
- plugin/src/helpers/files.ts
Removes a error logged when trying to resolve a module. This is not really an error, so logging it is confusing.
Fixes #291
> fix: remove confusing error log

- plugin/src/helpers/files.ts
**Which problem is this pull request solving?**
Gatsby uses some native binaries our SSR/DSG lambdas, most importantly the lmdb database engine. To handle differing ABI versions between the node versions in build machines and lambdas, we patch the Gatsby query engine bundle and manually copy binaries before deploying. A recent update to lmdb changed the name of the binary, which was correctly moved, but the bundle was not correctly patched, causing missing binaries when deployed.
**List other issues or pull requests related to this problem**
Fixes #294
**Describe the solution you've chosen**
I've fixed this by adding the new import string to the list of patches
> fix: patch new lmdb binary location

- release-please-config.json
Removing pinned version from Release Please config
> ci: remove pinned release please version

- .github/workflows/test.yml
**Which problem is this pull request solving?**
Adds a nightly cron job to run on the default/base (in this case `main`) branch.
**Describe the solution you've chosen**
Used the `on.schedule` configuration provided by [Github Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule)
**Checklist**
seen below.
> ci: :sparkles: run tests on a nightly basis

- plugin/src/helpers/cache.ts
Removing some debug code, as identified by @ascorbic
> chore: remove cache dir debug logs

- .github/workflows/add-to-project.yml
Adds an action that will automatically add new issues from this repo to the Ecosystem Frameworks project board
> chore: add automation for issues to project

- package-lock.json
- package.json
- plugin/package-lock.json
- plugin/package.json
- plugin/test/unit/helpers/functions.spec.ts
- plugin/test/unit/index.spec.ts
- chore: typed and fixed netlify config for tests
- chore: added types for chance package
- chore: auto fixed import order
Some types were incorrect for NetlifyConfig with the updates in #540. I also noticed the chance types were missing so added them as well.
This supersedes #540
1. This only affects tests, so if all is green. 🚢 
---
> chore: typed and fixed netlify config for tests
